build-FunctionHandlerFunction:
	cp -R . $(ARTIFACTS_DIR)
	rm $(ARTIFACTS_DIR)/Makefile

build-ModuleHandlerFunction:
	cp -R . $(ARTIFACTS_DIR)
	rm $(ARTIFACTS_DIR)/Makefile

build-ScriptHandlerFunction:
	cp -R . $(ARTIFACTS_DIR)
	rm $(ARTIFACTS_DIR)/Makefile

build-ScriptHandlerFailingFunction:
	cp -R . $(ARTIFACTS_DIR)
	rm $(ARTIFACTS_DIR)/Makefile
