AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-lambda-powershell-runtime
##########################################################################
#  Globals & Parameters                                                  #
##########################################################################
Resources:
  ##########################################################################
  #  Lambda layers                                                         #
  ##########################################################################
  PwshRuntimeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Lambda Layer containing PowerShell
      ContentUri: ./source
      CompatibleRuntimes:
        - provided.al2
        - provided.al2023
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
# Optional AWS Systems Manager Parameter Store to store Layer ARN for referencing in further templates.
#  PwshRuntimeParameter:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Name: lambda-powershell-runtime-latest-version-arn
#      Description: PwshRuntime Layer Name
#      Type: String
#      Value: !Ref PwshRuntimeLayer

##########################################################################
#  OUTPUTS                                                               #
##########################################################################
Outputs:
  PwshRuntimeLayer:
    Value: !Ref PwshRuntimeLayer
    Description: PwshRuntimeLayer Layer ARN
